version: '3'
services:
  web:
    image: cantonerobin/modul300_ci-cd:latest
    build: .
    container_name: my-static-site
    restart: unless-stopped
    expose:
      - 80
    networks:
      - my-network

  reverse-proxy:
    image: nginx:latest
    container_name: my-reverse-proxy
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - my-network

networks:
  my-network:
